### ISSUE TITLE
Hack doesent work

### ISSUE THREAD

**Issue by StabbyAlbert** [zbot473/SurvivHacks#202]
Its just like, no cheat assets load

**Comment by ALEXXANDRO23** [comment]
true it does not work

**Comment by ClouDz1127** [comment]
i just dm the guy who makes it and he said hes working on it so the hacks might get fixed  soon

**Comment by WVVEY** [comment]
@ClouDz1127 anything? cause i dont want my KG to drop anymore
i mean i am already gud at surviv but it helps

**Comment by WVVEY** [comment]
@alexvornoffice can u help us with this?

**Comment by zbot473** [comment]
And it freezes

**Comment by ClouDz1127** [comment]
i got nothing from the guy so idk when theirs going to be a new update to the hacks

**Comment by alexvornoffice** [comment]
> @alexvornoffice can u help us with this?

what you want me to do? :)

**Comment by herbieLoaded** [comment]
fix it

**Comment by coder580** [comment]
please fix it

**Comment by TheSatanicAngeI** [comment]
please fix it

**Comment by charlie45** [comment]
;_; hack is dying...

**Comment by PowerOfFusion** [comment]
https://www.mediafire.com/file/0b0nkg2zbjf86t4/ChromeExtension_updated.rar/file

It's a bit older version, but it works ;)

**Comment by zbot473** [comment]
can someone send me the vars?

**Comment by zbot473** [comment]
@PowerOfFusion wdym

**Comment by TheSatanicAngeI** [comment]
@zbot473 I agree it does work but it freeze sometimes.


proof https://gyazo.com/b84a1e24c7c84f620840305363f93ecd 

@PowerOfFusion  thx


Also https://github.com/yarkoval/survivio-plus/tree/master

this guy the legend yarkoval I don't know if he "made" or "edited" a version but I SAW WITH MY OWN EYES before it gets patched this version of hack looks legit, it looks like you aren'te ven using hack like for streaming. It is super fluent and DOESN'T FREEZE 1 game on 20 I froze and I did more than 20 trust me. 

But now it is outdated...can someone fix it please ?

**Comment by TheSatanicAngeI** [comment]
@PowerOfFusion  Are you getting this error too ?

`Uncaught TypeError: Cannot read property '#<Object>' of undefined
    at _0x1663d5.value (<anonymous>:1:205516)
    at _0x1663d5.value (<anonymous>:1:224839)
    at autoAimRenderCb (<anonymous>:1:155702)
    at s._0x19b650.(/anonymous function).render (<anonymous>:1:188190)
    at r._t (<anonymous>:1:960839)
    at r.c (<anonymous>:1:960470)
    at i.update (<anonymous>:2:32304)
    at t.emit (<anonymous>:52:92407)
    at t.update (<anonymous>:46:105179)
    at _tick (<anonymous>:46:103362)`

**Comment by PowerOfFusion** [comment]
@TheSatanicAngeI 
http://www.mediafire.com/file/66ab6zqncszavch/ChromeExtension.rar/file

**Comment by alexvornoffice** [comment]
do the game lags for you? it lags for me after the update as hell, with or with out hacks....

**Comment by TheSatanicAngeI** [comment]
@PowerOfFusion  Are you the one who implemented variables finding stuff in the console ?

**Comment by TheSatanicAngeI** [comment]
@PowerOfFusion  `---- Variable Finder ----
VM52:1 {menu: "Me", camera: "J", bullets: "Fe", objectCreator: "mt", map: "Oe", …}activePlayer: {main: "ut", netData: "$", localData: "ee"}bullets: "Fe"camera: "J"input: {main: "ke"}map: "Oe"menu: "Me"objectCreator: "mt"playerBarn: {main: "Le"}__proto__: Object`

**Comment by alexvornoffice** [comment]
I remember he said he purchased the hack but how to update variables even if you got them? I think he did not implemented that but will be nice to see the code to how it works..,

**Comment by TheSatanicAngeI** [comment]
Why would you purchase something that is broken

**Comment by zbot473** [comment]
@alexvornoffice who purchased it?

**Comment by alexvornoffice** [comment]
> @alexvornoffice who purchased it?

PowerOfFusion

**Comment by alexvornoffice** [comment]
BTW my custom hack is 99% done, I created from scratch! take a look at my play - https://drive.google.com/file/d/1Of3hmONJN0oPEcVakkTCkPrrlkYfhgSG/view

I lost the game because of mp200 "hell" a lot of player use mosin and shotguns, I hate them XD

**Comment by PowerOfFusion** [comment]
@alexvornoffice 
Only question for what?
The problem is how to re-load files (app.js, vendor.js, manifest.js).
Just load them differently(without editing) and the problem is the same.

**Comment by alexvornoffice** [comment]
You mean why it does not freeze? It has a different aproach I did not use the same model but a new one, I don't even have to update variables every day... :D

**Comment by TheSatanicAngeI** [comment]
@alexvornoffice  How so ?

**Comment by TheSatanicAngeI** [comment]
@alexvornoffice  
### Here's my proposition...

_Once you finish working on the hack..._

1. Making it **free** would be too much work for literally no gain so I don't recommend that.

2. Making it **paid** would only target a smaller audience since I believe most people looking for hacks on a io game are below 18 and so can't use online currency. BUT it would benefit your work and give you motivation to keep it updated. 

So what I suggest would be this.

3. Making it **advertising** to use. 

- Basically use shorten urls. But yes this comes with complications. First of I'd recommend this : https://bitly.com/ it's simple to use and work fine. 

But the problem that comes up is that you need to find a way to make people use that link to redirect on the hack. 
But doing so would allow people  to see the link to the thread if it is on github which would allow them to just save it and so refrain you from getting "ad revenue" sort of speaking.

Soooo if github doesn't have a function to hide your directory unless you have a direct link or get a clone download from the directory without acessing the thread itself it would be pointless.

For the question about "issues with the hack" well as simple as this you could create a Discord server where you not only advertise the link for the hack but make a channel to discuss issues. 


Example : http://bit.ly/6942069420

Or you could go for a less money eater tool like this one  : https://t2mio.com/ or https://www.bl.ink or https://tiny.cc

**Comment by TheSatanicAngeI** [comment]
@PowerOfFusion account as been deleted. 


Also `Uncaught TypeError: Cannot read property '4163' of undefined
    at _0x358eaa.value (<anonymous>:1:205693)
    at _0x358eaa.value (<anonymous>:1:225057)
    at autoAimRenderCb (<anonymous>:1:155802)
    at s._0x1abf18.(/anonymous function) [as render] (<anonymous>:1:188091)
    at r.St (<anonymous>:1:961583)
    at r.c (<anonymous>:1:961214)
    at i.update (<anonymous>:2:32355)
    at t.emit (<anonymous>:52:92407)
    at t.update (<anonymous>:46:105179)
    at _tick (<anonymous>:46:103362)`

**Comment by charlie45** [comment]
well I can see the hack is coming back soon

**Comment by Exerciz** [comment]
@alexvornoffice Would you sell it for 5$ ?

**Comment by Exerciz** [comment]
@alexvornoffice If you would sell it please let me know, i'm really intersted in it.
@zbot473 Or if you can update yours or make private one could also pay for it..

**Comment by zbot473** [comment]
Ok
